nginx1:
    image: nginx:1.12-alpine
    container_name: nginx1
    ports: 
        - "80:80"
        - "443:443"
    expose:
        - '80'
        - '443'
    volumes:
        - "/data/:/data/"
        - "/data1/:/data1/"
        - "/data2/:/data2/"
        - "/data2/nginx/conf/:/etc/nginx/"
        - "/data-dev/:/data-dev/"

