php1:
    #build: ./php
    #image: php:7.1-fpm-alpine
    image: php-fpm-composer:1.0
    container_name: dev_php1
    expose: 
        - "9000"
    volumes:
        - "/data-dev/data1/:/data1/"
        - "/data-dev/data2/:/data2/"
        - "/data-dev/data2/php/conf/:/usr/local/etc/"
    links:
        - mysql1:server_mysql

mysql1:
    image: mysql/mysql-server:5.7.20
    container_name: dev_mysql1
    ports:
        - "11308:11308"
    expose: 
        - "11308"
    volumes:
        - "/data-dev/data1/:/data1/"
        - "/data-dev/data2/:/data2/"
        - "/data-dev/data2/mysql/conf/:/etc/mysql/"
    environment: 
        - MYSQL_ROOT_PASSWORD=123456789

redis1:
    image: redis:3.2.11-alpine
    #build: ./redis
    container_name: dev_redis1
    ports: 
        - "12301:12301"
    expose:
        - "12301"
    volumes:
        - "/data-dev/data1/:/data1/"
        - "/data-dev/data2/:/data2/"
    command: redis-server /data2/redis/conf/12301.conf
    #command: redis-server
