ngxin:
    image: nginx:1.12-alpine
    container_name: nginx
    ports: 
        - "80:80"
        - "443:443"
    expose:
        - "80"
        - "443"
    volumes:
         - "/data1/sites/:/data/sites/"
         - "/data2/socks/:/data/socks/"
         - "/data3/logs/nginx/:/data/logs/"
         - "/data3/conf/nginx/:/etc/nginx/"
    restart: always

php:
    build: ./php
    #image: php:7.1-fpm-alpine
    container_name: php
    expose: 
        - "9000"
    volumes:
        - "/data1/sites/:/data/sites/"
        - "/data2/socks:/data/socks/"
        - "/data3/logs/php/:/data/logs/"
        - "/data3/conf/php/:/usr/local/etc/"
    links:
        - mysql:server_mysql

mysql:
    image: mysql/mysql-server:5.7.20
    container_name: mysql
    expose: 
        - "11308"
    volumes:
        - "/data2/socks:/data/socks/"
        - "/data2/db/mysql/:/data/db/"
        - "/data3/conf/mysql/:/etc/mysql/"
        - "/data3/logs/mysql:/data/logs/"
        - "/data3/backup/mysql:/data/backup/"
    environment: 
        - MYSQL_ROOT_PASSWORD=123456789
